apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-dynamo-lab

resources:
- ../../base
- networkpolicy-local.yaml
- dynamodb-local.yaml
- dynamodb-service.yaml

images:
- name: python-dynamo-lab-app-image
  newName: rshiva86/devopsrt-homelab-local
  newTag: 75efc785ab34b5fd56e7b989676713da6998dbd2

patches:
- path: deployment-patch.yaml
