apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-dynamo-lab

resources:
   - ../../base
   - networkpolicy-local.yaml
   - dynamodb-local.yaml
   - dynamodb-service.yaml

images:
   - name: python-dynamo-lab-app-image
     newName: python-dynamo-lab
     newTag: local

patches:
  - path: deployment-patch.yaml
