# alice → deploy-editor
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-editor
  namespace: python-dynamo-lab
rules:
  - apiGroups: ["apps"]
    resources: ["deployments","deployments/scale"]
    verbs:  ["get","list","watch","update","patch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods","pods/log"]
    verbs: ["get","list","watch"]


---
#bob → deploy-viewer

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-viewer
  namespace: python-dynamo-lab
rules:
  # Read-only on everything an on-call engineer needs to observe
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs:     ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "endpoints"]
    verbs:     ["get", "list", "watch"]
